import { Header } from '@/components/shared/header'
import { Links } from '@/components/shared/links'
import { ThemeProvider } from '@/components/shared/theme-provider'
import { ThemeToggle } from '@/components/shared/theme-toggle'
import { Toaster as Sonner } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import './globals.css'
import React from 'react'
import { TonProvider } from '@/components/shared/ton'

const inter = Inter({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'Ryazan market',
  description: 'Generated by create next app'
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' }
  ]
}

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-secondary-background')}>
        <TonProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Sonner />
            <Header className="bg-background">
              <Link href="/" className="flex items-center gap-2">
                <Image
                  src="/logo.svg"
                  alt="FSPHub Logo"
                  width={32}
                  height={32}
                  priority
                  className="dark:hidden"
                />
                <Image
                  src="/logo.svg"
                  alt="FSPHub Logo"
                  width={32}
                  height={32}
                  priority
                  className="hidden dark:block"
                />
              </Link>
              <div className="flex items-center justify-between gap-5 flex-col md:flex-row">
                <Links />
                <ThemeToggle />
              </div>
            </Header>
            <main className="min-h-[calc(100vh-78px)]">{children}</main> {modal}
          </ThemeProvider>
        </TonProvider>
      </body>
    </html>
  )
}
